### ISSUE TITLE
Александр, подскажите, пожалуйста, были ли случаи бана аккаунта?

### ISSUE THREAD

**Issue by j-zhrv** [Alexell/HH-Resumes-Updater#1]
Александр, здравствуйте! Подскажите, пожалуйста, были ли случаи бана аккаунта?

Когда мой знакомый делал парсер резюме (при платном доступе к базе резюме) hh банил жестко. Ему приходилось изворачиваться.

Спасибо большое за инструмент, кстати, планирую попробовать после Вашего ответа. Спасибо что поделились!

**Comment by Alexell** [comment]
@e-zhrv не могу знать наверняка, но не думаю что будут баны.
Во первых для обновления резюме на hh даже есть API, значит так делать можно. Пусть я его и не использую, но обновление страниц прога делает редко. По идее достаточно незаметно.
