### ISSUE TITLE
VirusTotal говорит что "23 антивируса отметили этот файл как вредоносный"

### ISSUE THREAD

**Issue by j-zhrv** [Alexell/HH-Resumes-Updater#2]
Александр,
VirusTotal говорит что "23 антивируса отметили этот файл как вредоносный"
https://www.virustotal.com/gui/file/b992fe4236cb35b74774e64957cba44afe4e4fff60c71156b749bad8f91714ec/detection

**Comment by Alexell** [comment]
@e-zhrv у программы открытый исходный код, вы в точности можете видеть что она делает и что в ней нет ничего вредоносного.
