### ISSUE TITLE
Не работает вход в аккаунт

### ISSUE THREAD

**Issue by sudmed** [Alexell/HH-Resumes-Updater#3]
При запуске программы встроенный браузер ведет веб странно.
На самом первом экране жму ссылку "Войти" - во встроенном браузере происходит переход на страницу авторизации, я ввожу свой email и вот тут уже не ссылка, а кнопка "Продолжить", не работает (не нажимается).  
  
![2022-09-24_22-57-35](https://user-images.githubusercontent.com/15969654/192116262-0aab716c-d1ed-4612-bba3-50e5c74709a7.png)

**Comment by Alexell** [comment]
Добрый день. Сейчас у меня нет возможности проверить эту проблему, скорее всего что-то по части javascript не проходит. Но это новая форма входа, ее не было на момент разработки программы. Думаю если вы нажмете справа "Войти с паролем", то все получится.

**Comment by sudmed** [comment]
Нажатие на ссылку "Войти с паролем" - тоже не работает. 
Не написал об этом сразу, т.к. посчитал это очевидным.

**Comment by Alexell** [comment]
Понял. Проверю, как появится возможность.

**Comment by Alexell** [comment]
Причина проблемы выявлена, HH прекратил поддержку Internet Explorer на уровне javascript, а тут использовался ActiveX компонент этого браузера.
Уже работаю над переходом на Microsoft Edge WebView2.

**Comment by Alexell** [comment]
[Релиз выпущен](https://alexell.ru/soft/other/avtopodnyatie-rezyume-na-headhunter.html).
