### ISSUE TITLE
Авторизацию проходит, но резюме не поднимает

### ISSUE THREAD

**Issue by sudmed** [Alexell/HH-Resumes-Updater#4]
Программа запускается, авторизовываюсь по логину-паролю. Далее появляются последовательно статусы: "авторизация успешна", "авторизация в порядке", "могу поднять 1 резюме", "резюме подняты в 12:23". 
Но при заходе на сайт hh резюме остается неподнятым. Повторный перезапуск программы заканчивается тем же: в статусе написано поднято, по факту на сайте - нет.

![2022-09-29_12-24-31](https://user-images.githubusercontent.com/15969654/192995720-a641da1f-d3e2-487c-8dbe-eb2ef49a77f2.png)

**Comment by Alexell** [comment]
Добрый день. Прошу прощения за столь долгий ответ.
Проверил сейчас повторно - все работает. У меня Windows 10. Сделал запись экрана: https://youtu.be/wco8cch7lWA
Возможно в вашем браузере Edge установлены какие-то ограничения на выполнение javascript? Могу только посоветовать проверить настройки Edge, может быть там какие-то ограничения в конфиденциальности включены.
Отпишитесь пожалуйста по результатам.

**Comment by sudmed** [comment]
Добрый день! Спасибо за ответ, буду разбираться с эджем.

**Comment by sudmed** [comment]
Проблема рассосалась сама после добавления второго резюме. Вероятно эти два события просто совпали, но сейчас все работает. Спасибо за программу!

**Comment by Alexell** [comment]
Рад что все получилось!
