### ISSUE TITLE
Консольная версия под Linux

### ISSUE THREAD

**Issue by syrovezhko** [Alexell/HH-Resumes-Updater#5]
## Не могли бы портировать под Linux? 

В идеале хотелось бы подключиться по SSH к Raspberry PI, запустить приложение, залогиниться на hh и оставить работать в фоне. Если будет возможность сохранять учетные данные и добавить приложение в автозагрузку - вообще супер.

> **Сценарий работы: один раз залогиниться, добавить в автозагрузку и наслаждаться её незаметной работой параллельно с медиаплеером Kodi.**

_**p.s.: если это показалось слишком навязчивым, прошу прощения, не хотел обидеть. 
p.p.s.: если что, готов помочь с тестированием. У меня RPI 3 B+ с libreelec. Без проблем накачу raspbian или иную ОС.**_

**Comment by Alexell** [comment]
Добрый день. К сожалению, портировать не получится, т.к. в качестве браузерного компонента используется виндовый Microsoft Edge WebView2. Что же касается линукса, уже есть примерно то что вы хотите, только нужно авторизовываться не логином и паролем, а через hh api. Ссылка: https://github.com/pavletto/refresh.hh
