### ISSUE TITLE
скрипт перестал работать

### ISSUE THREAD

**Issue by maxim43g** [Alexell/HH-Resumes-Updater#6]
можете исправить?

**Comment by Alexell** [comment]
Проверил, все работает. В чем именно у вас проблема?

**Comment by maxim43g** [comment]
> Проверил, все работает. В чем именно у вас проблема?

спасибо за обратную связь. 
Действительно, на Win 10 всё работает. 
На Win 7 - нет. Даёт выбрать страну, далее серое пустое окно, снизу написано "Авторизутейсь в этом браузере"

**Comment by Alexell** [comment]
Видимо это потому что на Windows 7 нету Microsoft Edge. Он нужен, т.к. для работы мини-браузера используется его компонент. К сожалению, у меня нет ни одного ПК с Windows 7, поэтому не могу сказать больше.

**Comment by jooblex** [comment]
Без edge никак?

**Comment by Alexell** [comment]
Других встроенных в RAD Studio браузерных компонентов нет, а сторонние изучать мне пока некогда.

**Comment by jooblex** [comment]
Не хватает автозапуска и авто-сворачивание в трей

**Comment by Alexell** [comment]
> Не хватает автозапуска и авто-сворачивание в трей

Сделал. Обновление можете скачать [здесь](https://github.com/Alexell/HH-Resumes-Updater/releases/tag/v2.0.1) или [здесь](https://alexell.ru/soft/other/avtopodnyatie-rezyume-na-headhunter.html).

**Comment by jooblex** [comment]
Я и не думал, что ты это сделаешь. Тогда может быть ещё что нибудь предложу
