### ISSUE TITLE
Вопрос про формулировку коммита "Добавлена иконка программы и логотипы для UWP"

### ISSUE THREAD

**Issue by mediaexplorer74** [Alexell/HH-Resumes-Updater#7]
Привет от древнего паскалевца (лет так уж 30 не кодил на этом славном языке с именем Паскаль, эх). Клевая программулька, а то автоподнятие резюмешек же на HH фича платная стала, а каждые 4 часа лениво на HH логиниться и пинговать каж. позицию ручками =)

Подскажите, пожалуйста, а причем в комменте комита слово "UWP", если язык не c+ или c#? Появилась некая среда разработки, которая Паскаль теперь умеет в UWP собирать?

- Батарейкин aka MediaExplorer

**Comment by Alexell** [comment]
Добрый день. Лично я паскаль вообще не знаю. Программа написана на C++ в среде разработки Embarcadero RAD Studio, которая позволяет даже создавать мультиплатформенные проекты, которые можно билдить под iOS, Android и ПК.
Что касается UWP, видимо тоже умеет, но я лишь просто добавил иконки в проекте, не придавайте этому особого значения, вот скрин:
![Screenshot_1](https://github.com/Alexell/HH-Resumes-Updater/assets/25535043/42e03a6d-23a0-4cd2-b8c1-48085485e88d)

**Comment by mediaexplorer74** [comment]
> Добрый день. Лично я паскаль вообще не знаю. Программа написана на C++ в среде разработки Embarcadero RAD Studio, которая позволяет даже создавать мультиплатформенные проекты, которые можно билдить под iOS, Android и ПК. Что касается UWP, видимо тоже умеет, но я лишь просто добавил иконки в проекте, не придавайте этому особого значения <...>

Вас понял. Сорян, про Паскаль я че-то не то загнул (старые глаза выцепили взглядом в солюшне лишь dfm файлы с содержимым форм, а на cpp замылились наглухо!!!). Про Embarcadero RAD Studio покурю / погуглю инфу, прям IDE-Франкенштейн какой то. На скришноше Вашем вижу настройки Delphi Compiler и Плюсов в одном флаконе, прям чудесно! )))) И да, походу, там есть мой любимый UWP , раз есть настройки иконок... Надо будет успеть при жизни поиграться с этим любопытным продуХтом, смастерить что-нить кросс-платформенное с душою Delph-ей , а то 25 лет все Вижуал Студио да Студио одна... ;)
Портировал , вообщим, Ваш алгоритм под шарпы, и на своем вин-ноуте или прям на своем ретрофоне Люмка 950 терь могу в uwp-приложеньке одной кнопкой поднимать все свои 10 HH-резюмешек. Спасибо Вам большое. А, еще нуно будет таймер прикрутить и фоновый task, и потом смерджить со своим брошенным в том году проектом HHExplorer
С уважением,
Андрей

**Comment by Alexell** [comment]
Ну если вы знаете Delphi, то в RAD Studio сможете писать и на нем (при установке выберете Delphi вместо C++). Удачи вам!
