### ISSUE TITLE
Несовместимость с windows 11

### ISSUE THREAD

**Issue by o-200** [Alexell/HH-Resumes-Updater#8]
На windows 11 программа не работает. 

1. Резюме не обновляются
2. Есть проблема с кодировкой шрифтов (чек скрин)

![image_2023-06-27_18-35-06](https://github.com/Alexell/HH-Resumes-Updater/assets/34093966/88a034d1-8fa3-4d39-992a-7f07aa089288)

**Comment by Alexell** [comment]
Здравствуйте. Я не смогу сделать поддержку Windows 11, пока сам на нее не перейду. А делать этого я пока не собираюсь.

**Comment by o-200** [comment]
> Здравствуйте. Я не смогу сделать поддержку Windows 11, пока сам на нее не перейду. А делать этого я пока не собираюсь.

Оказалось, что проблема не в windows, а в кодировке символов. У меня стоит windows 11 английской версии, которая изначально не поддерживает кодировку символов для русских символов. После того как я подключил пакет русского языка - программа заработала.

**Comment by Alexell** [comment]
Аа, вот в чем было дело. Что ж, будем знать. Сасибо за информацию.
